# Generated by Django 6.1 on 2026-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("SELLER", "Seller"),
                    ("ADMIN", "Admin"),
                ],
                db_index=True,
                default="CUSTOMER",
                max_length=20,
                null=True,
            ),
        ),
    ]
