# Generated by Django 6.1 on 2026-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("node_name", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("node", models.UUIDField(db_index=True, editable=False, unique=True)),
                ("parent", models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpectrumData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "node_id",
                    models.UUIDField(db_index=True, editable=False, unique=True),
                ),
                ("data", models.BinaryField()),
            ],
        ),
    ]
