# Generated by Django 6.1 on 2026-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_inegstion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_name", models.CharField(max_length=255)),
                ("sensor_type", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("value", models.FloatField(default=0.0)),
            ],
        ),
    ]
