# Generated by Django 6.1 on 2026-09-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
