# Generated by Django 6.1 on 2026-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                editable=False, max_length=160, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
